# Generated by Django 3.2.6 on 2021-08-14 08:04

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(posts.models.get_sentinel_category), to='categories.categorie'),
        ),
    ]
