# Generated by Django 3.2.6 on 2021-08-18 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0002_alter_gallerie_id'),
        ('blog', '0005_tag_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='categorie',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='galleries.gallerie'),
        ),
    ]
