# Generated by Django 3.2.6 on 2021-08-21 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0002_alter_gallerie_id'),
        ('blog', '0006_auto_20210818_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='galleries.gallerie'),
        ),
    ]
